INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (0 , now(), now(), '품종을 모르는 경우입니다.', 'Unknown', 'UNKNOWN');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '골든 리트리버', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '포메라니안', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '시베리안 허스키', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '치와와', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '푸들', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '말티즈', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '재패니스 스피츠', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '토이푸들', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '시츄', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '비숑 프리제', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '닥스훈트', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '아메리칸 코카 스파니엘', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '요크셔테리어', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '래브라도 리트리버', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '보더콜리', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '비글', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '미니어쳐 핀셔', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '진돗개', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '꼬똥드툴레아', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '보스턴테리어', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '카디건 웰시코기', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '알래스카 말라뮤트', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '빠삐용', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '삽살개', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '펨브록 웰시 코기', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '라이카', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '아메리칸코카스파니엘', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '도베르만', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '풍산개', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '슈나우저', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '버니즈 마운틴 독', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '프렌치불독', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '샤페이', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '사모예드', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '올드 잉글리쉬 쉽독', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '페니키즈', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '브리타니 스파니엘', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '퍼그', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '케인 코르소', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '웨스트하이랜드화이트테리어', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '핏불테리어', 'DOG');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '저먼 세퍼드 독', 'DOG');

INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '노르웨이숲고양이', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '데본렉스', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '라가머핀', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '라팜', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '랙돌', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '러시안블루', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '맹크스고양이', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '먼치킨', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '메인쿤', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '발리네즈', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '버만', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '버미즈', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '봄베이', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '브리티시 쇼트헤어', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '시베리아고양이', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '샴고양이', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '샤트룩스', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '셀커크 렉스', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '소말리', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '스코티시폴드', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '스핑크스', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '싱가퓨라', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '아메리칸밥테일', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '아메리칸쇼트헤어', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '아메리칸와이어헤어', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '아메리칸컬', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '아비시니안고양이', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '오리엔탈', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '오시캣', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '유러피안버미즈', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '이그저틱', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '이집션마우', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '자바니즈', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '재패니즈밥테일', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '컬러포인트쇼트헤어', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '코니시 렉스', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '코랫', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '터키시반', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '터키시앙고라', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '통키니즈', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '페르시안고양이', 'CAT');
INSERT INTO pet_kind (pet_kind_id, created_at, updated_at, information, pet_kind_name, pet_type) values (default , now(), now(), '', '하바나브라운', 'CAT');
